### ISSUE TITLE
raise KeyError(key) from None

### ISSUE THREAD

**Issue by tinoargentino** [neoterix/nyc-mta-arrival-notify#1]
Hi!

I'm running into an error loading the .env

I get the following message:

> > Traceback (most recent call last):
>   File "mta_notification.py", line 10, in <module>
>     api_key = os.environ['API_KEY']
>   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 678, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'API_KEY'

Do you know what's the problem?

**Comment by tinoargentino** [comment]
I think I solved it, I had to change the name of the file to only .env

**Comment by wblummer32** [comment]
@tinoargentino I am running into the same issue.  Is there anything else you changed in the script itself?  I renamed the .env file to ".env" but I am still getting this error.

**Comment by wblummer32** [comment]
There is a good explanation for this [here](https://stackoverflow.com/questions/41125023/how-to-use-python-dotenvs-find-dotenv-method)
