### ISSUE TITLE
KeyError: 'stop_time_update'

### ISSUE THREAD

**Issue by mhgwilliams** [neoterix/nyc-mta-arrival-notify#2]
I've tried a few github projects using the mta api and am running into the same issue in multiple. 
When running in normal configuration, nothing changed, I get this error:

```
Traceback (most recent call last):
  File "mta_notification.py", line 46, in <module>
    station_time_lookup(realtime_data, 'R36N')
  File "mta_notification.py", line 37, in station_time_lookup
    unique_arrival_times = unique_train_schedule['stop_time_update'] # arrival_times is a list of arrivals
KeyError: 'stop_time_update'
```

This is some sort of dictionary error, but I don't understand why it doesn't see this key when I can see it fine when printing that data.

Is it something to do with processing power? I'm running this on a Raspberry pi zero, quite low powered.

**Comment by effeappbw** [comment]
I've found one potential cause/band-aid, but I'm not experienced enough to fix the bug. Increasing the time interval in the following line helped me:

Change the following line 
`if time_until_train > 3:` to `if time_until_train > 10:`

However, increasing it too much, say to 20 mins, results in the same error.
